version: '3'

services:
    db:
        image: mysql
        container_name: db_cesicar
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'api_cesicar'
            MYSQL_USER: 'api_cesicar'
            MYSQL_PASSWORD: 'api_cesicar'


    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmni_cesicar
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db

    www:
        build: .docker/services/www
        container_name: www_cesicar
        ports:
            - 8000:80
        volumes:
            - ./.docker/services/www/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
            - ./.docker/services/www/install:/install

volumes:
    db-data:
